# /// script
# requires-python = ">=3.12"
# dependencies = ["fonttools[woff]==4.66.0"]
# ///
"""Regenerate checked-in Latin fonts and CSS: uv run scripts/subset-fonts.py."""

from itertools import groupby
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1] / "src/sphinx_lumina_theme"
FONTS = ROOT / "theme/static/fonts"
# Latin, common punctuation, arrows, and the Mac search shortcut symbol.
UNICODES = (
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,"
    "U+0300-036F,U+2000-206F,U+20AC,U+2122,U+2190-2199,"
    "U+2212,U+2215,U+2318,U+FEFF,U+FFFD"
)


def main():
    css = [
        "/* Generated by scripts/subset-fonts.py. Full fonts cover other characters. */"
    ]
    unicodes = set(subset.parse_unicodes(UNICODES))
    for source in sorted(FONTS.glob("*.woff2")):
        if source.stem.endswith("-latin"):
            continue
        family = (
            "Source Sans 3"
            if source.stem.startswith("source-sans")
            else "JetBrains Mono"
        )
        weight = source.stem.rsplit("-", 1)[1].replace("regular", "400")
        target = source.with_stem(source.stem + "-latin")
        with TTFont(source, recalcTimestamp=False) as font:
            expected = set(font.getBestCmap()) & unicodes
            # Avoid downloading the full font for symbols it cannot render either.
            full_ranges = []
            for _, group in groupby(
                enumerate(sorted(font.getBestCmap())), lambda item: item[1] - item[0]
            ):
                points = [code for _, code in group]
                full_ranges.append(f"U+{points[0]:04X}-{points[-1]:04X}")
            options = subset.Options()
            options.layout_features = ["*"]
            # Retain copyright and license.
            options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
            subsetter = subset.Subsetter(options=options)
            subsetter.populate(unicodes=unicodes)
            subsetter.subset(font)
            font.save(target)
        with TTFont(target) as result:
            assert set(result.getBestCmap()) == expected, target
        print(
            f"{source.name}: {source.stat().st_size:,} → {target.stat().st_size:,} bytes"
        )
        # Last matching face wins: use the small font for Latin, the original otherwise.
        for path in (source, target):
            ranges = UNICODES if path == target else ",".join(full_ranges)
            css.append(
                f'@font-face {{\n  font-family: "{family}";\n  font-style: normal;\n'
                f"  font-weight: {weight};\n  font-display: swap;\n"
                f'  src: url("fonts/{path.name}") format("woff2");\n'
                f"  unicode-range: {ranges};\n}}"
            )
    (ROOT / "_static_src/css/fonts.css").write_text("\n\n".join(css) + "\n")


if __name__ == "__main__":
    main()
